DROP TABLE IF EXISTS testModule;

CREATE TABLE IF NOT EXISTS testModule (
	`id` INT (11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`userID` INT (11) UNSIGNED NOT NULL,
	`hasJob` TINYINT (1) NOT NULL
) ENGINE = MyISAM;